# netlify.toml ファイルをプロジェクトのルートに作成
[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./"

#[plugins]
#  package = "@netlify/plugin-nextjs"

# キャッシュの設定を追加
[[plugins]]
  package = "netlify-plugin-cache-nextjs"

#[build.environment]
#  NODE_VERSION = "18"
#  NPM_FLAGS = "--no-audit --no-fund"